apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
    spec:
      containers:
        - name: {{ .Values.global.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}