name: Helm package creation

on:
  workflow_dispatch:

env:
    REGISTRY: ghcr.io
    REMOTE_DEST: oci://ghcr.io/${{ github.actor }}

jobs:
  release-helm-artifacte:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set CHART_VERSION
        run: echo "CHART_VERSION=$(grep 'version:' ${{ github.workspace }}/deployment/Chart.yaml | tail -n1 | awk '{ print $2 }')" >> $GITHUB_ENV

      - name: Login to Helm registry
        run: |
          helm registry login ${{ env.REGISTRY }} --username ${{ github.actor }} --password ${{ secrets.GH_TOKEN }}

      - name: save Helm package to local registry
        run: |
          helm package ${{ github.workspace }}/deployment

      - name: Upload Helm package to remote registry
        run: |
          helm push ${{ github.event.repository.name }}-${{ env.CHART_VERSION }}.tgz ${{ env.REMOTE_DEST }}
 